namespace String.Exercises
{
    // Leetcode 389: Find the Difference
    // Link: https://leetcode.com/problems/find-the-difference/
    // Difficulty: Easy
    // Tags: Hash Table, String
    // Description:
        // You are given two strings s and t which consist of only lowercase letters. 
        // String t is generated by random shuffling string s and then adding one more letter at a random position.
        // Return the letter that was added to t.
    // Examples:
        // Example 1:
            // Input: s = "abcd", t = "abcde"
            // Output: "e"
            // Explanation: 'e' is the letter that was added.
        // Example 2:
            // Input: s = "", t = "y"
            // Output: "y"
        // Explanation: 'y' is the letter that was added.
    public class LC_389_FindTheDifference
    {
        public static char FindTheDifference(string s, string t)
        {
            Dictionary<char, int> exists = [];

            // a
            // a, 1. 
            foreach(char c in s)
            {
                if (!exists.ContainsKey(c))
                {
                    exists.Add(c, 1);
                }
                else 
                {
                    exists[c]++;
                }
            }

            // aa
            foreach(char c in t)
            {
                if (!exists.ContainsKey(c)) return c;
                exists[c]--;
                if (exists[c] < 0)
                {
                    return c;
                }
            }

            return ' ';
        }
    }
}